### ISSUE TITLE
Template does not found

### ISSUE THREAD

**Issue by slava-poddubsky** [spapas/wagtail-multi-upload#3]
When I add this dependency in my `requirements.txt`:
```
git+https://github.com/spapas/wagtail-multi-upload.git@master
```

and open admin page with `MultipleImagesPanel` (the library is specified in INSTALLED_APPS), next error message is shown:

```
Environment:


Request Method: GET
Request URL: http://0.0.0.0:8000/admin/pages/142/edit/

Django Version: 3.1.1
Python Version: 3.8.3
Installed Applications:
['core',
 'home',
 'owners',
 'about',
 'blog',
 'properties',
 'search',
 'wagtail.contrib.forms',
 'wagtail.contrib.redirects',
 'wagtail.embeds',
 'wagtail.sites',
 'wagtail.users',
 'wagtail.snippets',
 'wagtail.documents',
 'wagtail.images',
 'wagtail.search',
 'wagtail.admin',
 'wagtail.core',
 'modelcluster',
 'taggit',
 'storages',
 'sass_processor',
 'phonenumber_field',
 'robots',
 'wagtailmarkdown',
 'wagtailgeowidget',
 'wagtail_multi_upload',
 'django.contrib.admin',
 'wagtail.contrib.modeladmin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'wagtail.contrib.styleguide',
 'wagtail.contrib.settings',
 'wagtail.contrib.search_promotions']
Installed Middleware:
['middlewares.healthcheck.HealthCheckMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'wagtail.contrib.redirects.middleware.RedirectMiddleware']

Template loader postmortem
Django tried loading these templates, in this order:

Using engine django:
    * django.template.loaders.filesystem.Loader: /code/templates/wagtail_multi_upload/edit_handlers/multiple_images_panel.html (Source does not exist)
    * django.template.loaders.app_directories.Loader: /code/search/templates/wagtail_multi_upload/edit_handlers/multiple_images_panel.html (Source does not exist)
    * django.template.loaders.app_directories.Loader: /usr/local/lib/python3.8/site-packages/wagtail/contrib/forms/templates/wagtail_multi_upload/edit_handlers/multiple_images_panel.html (Source does not exist)
    * django.template.loaders.app_directories.Loader: /usr/local/lib/python3.8/site-packages/wagtail/contrib/redirects/templates/wagtail_multi_upload/edit_handlers/multiple_images_panel.html (Source does not exist)
    * django.template.loaders.app_directories.Loader: /usr/local/lib/python3.8/site-packages/wagtail/embeds/templates/wagtail_multi_upload/edit_handlers/multiple_images_panel.html (Source does not exist)
    * django.template.loaders.app_directories.Loader: /usr/local/lib/python3.8/site-packages/wagtail/sites/templates/wagtail_multi_upload/edit_handlers/multiple_images_panel.html (Source does not exist)
    * django.template.loaders.app_directories.Loader: /usr/local/lib/python3.8/site-packages/wagtail/users/templates/wagtail_multi_upload/edit_handlers/multiple_images_panel.html (Source does not exist)
    * django.template.loaders.app_directories.Loader: /usr/local/lib/python3.8/site-packages/wagtail/snippets/templates/wagtail_multi_upload/edit_handlers/multiple_images_panel.html (Source does not exist)
    * django.template.loaders.app_directories.Loader: /usr/local/lib/python3.8/site-packages/wagtail/documents/templates/wagtail_multi_upload/edit_handlers/multiple_images_panel.html (Source does not exist)
    * django.template.loaders.app_directories.Loader: /usr/local/lib/python3.8/site-packages/wagtail/images/templates/wagtail_multi_upload/edit_handlers/multiple_images_panel.html (Source does not exist)
    * django.template.loaders.app_directories.Loader: /usr/local/lib/python3.8/site-packages/wagtail/search/templates/wagtail_multi_upload/edit_handlers/multiple_images_panel.html (Source does not exist)
    * django.template.loaders.app_directories.Loader: /usr/local/lib/python3.8/site-packages/wagtail/admin/templates/wagtail_multi_upload/edit_handlers/multiple_images_panel.html (Source does not exist)
    * django.template.loaders.app_directories.Loader: /usr/local/lib/python3.8/site-packages/wagtail/core/templates/wagtail_multi_upload/edit_handlers/multiple_images_panel.html (Source does not exist)
    * django.template.loaders.app_directories.Loader: /usr/local/lib/python3.8/site-packages/robots/templates/wagtail_multi_upload/edit_handlers/multiple_images_panel.html (Source does not exist)
    * django.template.loaders.app_directories.Loader: /usr/local/lib/python3.8/site-packages/django/contrib/admin/templates/wagtail_multi_upload/edit_handlers/multiple_images_panel.html (Source does not exist)
    * django.template.loaders.app_directories.Loader: /usr/local/lib/python3.8/site-packages/wagtail/contrib/modeladmin/templates/wagtail_multi_upload/edit_handlers/multiple_images_panel.html (Source does not exist)
    * django.template.loaders.app_directories.Loader: /usr/local/lib/python3.8/site-packages/django/contrib/auth/templates/wagtail_multi_upload/edit_handlers/multiple_images_panel.html (Source does not exist)
    * django.template.loaders.app_directories.Loader: /usr/local/lib/python3.8/site-packages/wagtail/contrib/styleguide/templates/wagtail_multi_upload/edit_handlers/multiple_images_panel.html (Source does not exist)
    * django.template.loaders.app_directories.Loader: /usr/local/lib/python3.8/site-packages/wagtail/contrib/settings/templates/wagtail_multi_upload/edit_handlers/multiple_images_panel.html (Source does not exist)
    * django.template.loaders.app_directories.Loader: /usr/local/lib/python3.8/site-packages/wagtail/contrib/search_promotions/templates/wagtail_multi_upload/edit_handlers/multiple_images_panel.html (Source does not exist)


Template error:
In template /usr/local/lib/python3.8/site-packages/wagtail/admin/templates/wagtailadmin/edit_handlers/multi_field_panel.html, error at line 5
   wagtail_multi_upload/edit_handlers/multiple_images_panel.html
   1 : <fieldset>
   2 :     <legend>{{ self.heading }}</legend>
   3 :     <ul class="fields">
   4 :         {% for child in self.children %}
   5 :             <li class="{{ child.classes|join:" " }}"> {{ child.render_as_field }} </li>
   6 :         {% endfor %}
   7 :     </ul>
   8 : </fieldset>
   9 : 

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/defaulttags.py", line 211, in render
    nodelist.append(node.render_annotated(context))
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 988, in render
    output = self.filter_expression.resolve(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 671, in resolve
    obj = self.var.resolve(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 796, in resolve
    value = self._resolve_lookup(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 858, in _resolve_lookup
    current = current()
  File "/usr/local/lib/python3.8/site-packages/wagtail/admin/edit_handlers.py", line 213, in render_as_field
    return self.render()
  File "/usr/local/lib/python3.8/site-packages/wagtail_multi_upload/edit_handlers.py", line 38, in render
    formset = render_to_string(self.template, context)
  File "/usr/local/lib/python3.8/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/local/lib/python3.8/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)

The above exception (wagtail_multi_upload/edit_handlers/multiple_images_panel.html) was the direct cause of the following exception:
  File "/usr/local/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/defaulttags.py", line 211, in render
    nodelist.append(node.render_annotated(context))
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 988, in render
    output = self.filter_expression.resolve(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 671, in resolve
    obj = self.var.resolve(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 796, in resolve
    value = self._resolve_lookup(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 858, in _resolve_lookup
    current = current()
  File "/usr/local/lib/python3.8/site-packages/wagtail/admin/edit_handlers.py", line 206, in render_as_object
    return self.render()
  File "/usr/local/lib/python3.8/site-packages/wagtail/admin/edit_handlers.py", line 309, in render
    return mark_safe(render_to_string(self.template, {
  File "/usr/local/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/local/lib/python3.8/site-packages/django/template/backends/django.py", line 63, in render
    reraise(exc, self.backend)
  File "/usr/local/lib/python3.8/site-packages/django/template/backends/django.py", line 84, in reraise
    raise new from exc

The above exception (wagtail_multi_upload/edit_handlers/multiple_images_panel.html) was the direct cause of the following exception:
  File "/usr/local/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/defaulttags.py", line 211, in render
    nodelist.append(node.render_annotated(context))
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 988, in render
    output = self.filter_expression.resolve(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 671, in resolve
    obj = self.var.resolve(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 796, in resolve
    value = self._resolve_lookup(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 858, in _resolve_lookup
    current = current()
  File "/usr/local/lib/python3.8/site-packages/wagtail/admin/edit_handlers.py", line 206, in render_as_object
    return self.render()
  File "/usr/local/lib/python3.8/site-packages/wagtail/admin/edit_handlers.py", line 309, in render
    return mark_safe(render_to_string(self.template, {
  File "/usr/local/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/local/lib/python3.8/site-packages/django/template/backends/django.py", line 63, in render
    reraise(exc, self.backend)
  File "/usr/local/lib/python3.8/site-packages/django/template/backends/django.py", line 84, in reraise
    raise new from exc

The above exception (wagtail_multi_upload/edit_handlers/multiple_images_panel.html) was the direct cause of the following exception:
  File "/usr/local/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 988, in render
    output = self.filter_expression.resolve(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 671, in resolve
    obj = self.var.resolve(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 796, in resolve
    value = self._resolve_lookup(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 858, in _resolve_lookup
    current = current()
  File "/usr/local/lib/python3.8/site-packages/wagtail/admin/edit_handlers.py", line 238, in render_form_content
    return mark_safe(self.render_as_object() + self.render_missing_fields())
  File "/usr/local/lib/python3.8/site-packages/wagtail/admin/edit_handlers.py", line 206, in render_as_object
    return self.render()
  File "/usr/local/lib/python3.8/site-packages/wagtail/admin/edit_handlers.py", line 309, in render
    return mark_safe(render_to_string(self.template, {
  File "/usr/local/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/local/lib/python3.8/site-packages/django/template/backends/django.py", line 63, in render
    reraise(exc, self.backend)
  File "/usr/local/lib/python3.8/site-packages/django/template/backends/django.py", line 84, in reraise
    raise new from exc

The above exception (wagtail_multi_upload/edit_handlers/multiple_images_panel.html) was the direct cause of the following exception:
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 202, in _get_response
    response = response.render()
  File "/usr/local/lib/python3.8/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python3.8/site-packages/django/template/response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "/usr/local/lib/python3.8/site-packages/django/template/backends/django.py", line 63, in render
    reraise(exc, self.backend)
  File "/usr/local/lib/python3.8/site-packages/django/template/backends/django.py", line 84, in reraise
    raise new from exc

Exception Type: TemplateDoesNotExist at /admin/pages/142/edit/
Exception Value: wagtail_multi_upload/edit_handlers/multiple_images_panel.html
```

Seems like `setup.py` does not copy all static and html files, because when I copy-pasted all github templates in my local templates folder, library works fine.

Thank you!

**Comment by spapas** [comment]
Hello, thank you for the heads up! In my project it was working because for some reason the missing files were in an `src` folder inside my virtualenvironment.

I've now modified setup.py to use the `MANIFEST.in` to also copy over the templates and static directories to the `venv\Lib\site-packages\wagtail_multi_upload` folder.

Best regards,
Serafeim
